fix #36: WebUI not working on 64 bit only devices
PerformanC/ReZygisk pull request #39
Opened 2024-07-25 11:56 UTC by miuirussia

## Changes

## Why 

Write here why you think this should be merged

## Checkmarks

- [*] The modified functions have been tested.
- [*] Used the same indentation as the rest of the project.

2024-07-25 12:19 UTC, miuirussia commented
@ThePedroo please, merge this fix

2024-07-25 12:21 UTC, RainyXeon commented
@miuirussia He's not online rn số u have to be patient

2024-07-25 21:42 UTC, ThePedroo requested changes

2024-07-25 21:42 UTC, ThePedroo commented on webroot/js/main.js
> +    const [version_line, _, process_line, daemon_running_or_root_impl_line, daemon_running_line] = ptrace64Cmd.stdout.split('\n')
```suggestion
    const [ version_line, _, process_line, daemon_running_or_root_impl_line, daemon_running_line ] = ptrace64Cmd.stdout.split('\n')
```

2024-07-25 21:42 UTC, ThePedroo commented on webroot/js/main.js
> +      root_impl.innerHTML = daemon_running_or_root_impl_line.split(': ')[1];
```suggestion
      root_impl.innerHTML = daemon_running_or_root_impl_line.split(': ')[1]
```

2024-07-25 21:42 UTC, ThePedroo commented on webroot/js/main.js
> +    const [version_line, _, process_line, daemon_running_or_root_impl_line, daemon_running_line] = ptrace32Cmd.stdout.split('\n')
Ditto

2024-07-25 21:42 UTC, ThePedroo commented on webroot/js/main.js
> +      root_impl.innerHTML = daemon_running_or_root_impl_line.split(': ')[1];
Ditto

2024-07-26 16:55 UTC, ThePedroo approved these changes
LGTM

2024-07-27 05:40 UTC, merged