improve: clean up some string caches on stack in ptracer
PerformanC/ReZygisk pull request #41
Opened 2024-07-31 02:46 UTC by Microwwbin

## Changes

Try to hide some traces of zygisk.

## Why 

This looks like a "found injection" check point. You can simply validate it by return directly in entry.cpp#entry.

2024-07-31 02:47 UTC, ThePedroo commented
Will look into it, thanks!

2024-07-31 19:20 UTC, ThePedroo requested changes
Quick look, only syntax changes. However I'd like, if possible, a simple POC of how this (stack /static strings) could be detected

2024-07-31 19:20 UTC, ThePedroo commented on loader/src/ptracer/ptracer.cpp
> +    auto len = strlen(path) + 1;
The goal of the project is to re-write it all to C99, so please avoid the use of C++ specific keywords.

2024-07-31 19:20 UTC, ThePedroo commented on loader/src/ptracer/ptracer.cpp
> +    regs.REG_SP += len;
Please break the line after and before regs.RED_SP

2024-07-31 19:20 UTC, ThePedroo commented on loader/src/ptracer/ptracer.cpp
> +static void clearStackStringData(int pid, struct user_regs_struct& regs, const char *path) {
`clearStackStringData` -> `hide_static_string` or `clear_static_string`

2024-07-31 19:20 UTC, ThePedroo commented on loader/src/ptracer/ptracer.cpp
> +    clearStackStringData(pid, regs, entry);
Ditto

2024-07-31 19:20 UTC, ThePedroo commented on loader/src/ptracer/ptracer.cpp
> +    clearStackStringData(pid, regs, lib_path);
Break the line after the func call

2024-09-03 07:43 UTC, Microwwbin commented
**Test on A13**
Dump the stack data with follow code:
```cpp
    std::ofstream dump_data("/data/data/<package_name>/cache/dump", std::ios::binary);
    if (dump_data.is_open())
        for (auto &map: lsplt::MapInfo::Scan()) {
            if ((/*map.path.find("anon:stack_and_tls") != std::string::npos ||*/
                        map.path.find("[stack]") != std::string::npos) &&
                (map.perms & PROT_READ)) {
                auto address = reinterpret_cast<char *>(map.start);
                for (; address < (void *) map.end; address++) {
                    if (*address) dump_data.write(reinterpret_cast<char *>(address), 1);
                }
                LOGD("has dumped %s", map.path.c_str());
            }
        }
    else
        LOGE("not open");
    dump_data.flush();
    dump_data.close();
```
In the dump file, would see:
![image](https://github.com/user-attachments/assets/b0713dde-1c24-4011-b860-32739d9f105d)

2024-09-03 08:05 UTC, Microwwbin commented
**Test on A13**
Dump the stack data with follow code:
```cpp
    std::ofstream dump_data("/data/data/<package_name>/cache/dump", std::ios::binary);
    if (dump_data.is_open())
        for (auto &map: lsplt::MapInfo::Scan()) {
            if ((/*map.path.find("anon:stack_and_tls") != std::string::npos ||*/
                        map.path.find("[stack]") != std::string::npos) &&
                (map.perms & PROT_READ)) {
                auto address = reinterpret_cast<char *>(map.start);
                for (; address < (void *) map.end; address++) {
                    if (*address) dump_data.write(address, 1);
                }
                LOGD("has dumped %s", map.path.c_str());
            }
        }
    else
        LOGE("not open");
    dump_data.flush();
    dump_data.close();
```
In the dump file, would see:
![60cd0d65-f1a4-48d3-814a-35da547f42a9](https://github.com/user-attachments/assets/34b22e3d-ac22-4725-861d-91ef767f6a99)

2024-09-04 09:56 UTC, Microwwbin commented
**Test on A13, confirmed this is one of "found injection" check point​**
Dump the stack data with follow code:​
```cpp
    std::ofstream dump_data("/data/data/<package_name>/cache/dump", std::ios::binary);
    if (dump_data.is_open())
        for (auto &map: lsplt::MapInfo::Scan()) {
            if ((/*map.path.find("anon:stack_and_tls") != std::string::npos ||*/
                        map.path.find("[stack]") != std::string::npos) &&
                (map.perms & PROT_READ)) {
                auto address = reinterpret_cast<char *>(map.start);
                for (; address < (void *) map.end; address++) {
                    if (*address) dump_data.write(address, 1);
                }
                LOGD("has dumped %s", map.path.c_str());
            }
        }
    else
        LOGE("not open");
    dump_data.flush();
    dump_data.close();
```
In the dump file, would see:
![image](https://github.com/user-attachments/assets/cc817590-4030-4e7d-9f75-7d8c8f403911)

2024-09-09 15:11 UTC, ThePedroo commented
If we mmap to then munmap, theorically yes. This could possibly be better as it removes entirely from memory maps, supposedly. Any thoughts on this, @Microwwbin?

2024-09-09 15:13 UTC, ThePedroo commented
Also, I don`t think debug_ramdisk string is coming from ReZygisk -- it has been a lot of time since we don`t use it anymore

2024-11-11 02:28 UTC, closed without merging

2024-11-11 02:29 UTC, ThePedroo commented
??? I did not even touch this PR.

2024-12-05 19:25 UTC, JingMatrix commented
I didn't find the string `debug_r` in the stack.