add: loader: injector: Recognize Zygisk modules with API version 5
PerformanC/ReZygisk pull request #72
Opened 2024-11-11 07:27 UTC by rmnscnce

PerformanC/ReZygisk@2017140 already updated the API to version 5 but the change was not reflected in neither the API header nor the injector

Refer to:
- https://github.com/topjohnwu/Magisk/commit/e35925d520b5fab3acc96c1f137f951edca06760#diff-d2c92e2ebb584ce9600c8e114697bf981c837bcd3f4e80266334a27eacd7dc4eR26
- https://github.com/topjohnwu/Magisk/commit/4931825912553d6d02b72221283f27f4474dad55#diff-919d4ee0afebedf05017af6875ef4ac18daa081de311d4097e8bf3b516f3bcf8R67

## Why 

Because modules that use the [latest API header found in the latest stable Magisk release](https://github.com/topjohnwu/Magisk/blob/v28.0/native/src/core/zygisk/api.hpp) are not getting loaded

## Checkmarks

- [x] The modified functions have been tested.
- [x] Used the same indentation as the rest of the project
  - Note: The API header was updated to be identical with the one found in https://github.com/topjohnwu/Magisk/tree/v28.0

2024-11-11 12:19 UTC, ThePedroo commented
That's why the last time I tried using built module from there to test Zygiskd C99 it didn't work 🤣

2024-11-22 20:04 UTC, ThePedroo commented
I'll review it again soon, but I'll likely to approve. However it still confuses me as I haven't seen any update from v4 to v5, and it's not in zygisk-module-sample repository.

2025-05-04 02:28 UTC, ThePedroo requested changes
I suppose this leaves me with no options but to accept, as if some developer use this in the future, it better support it. It seems the only change done here is in the specialize args.

Also, sorry for the delay, it will not happen again. All I need is this one change and I will merge it.

2025-05-06 10:22 UTC, rmnscnce commented
Since I don't have access to the environment I was using to create this PR for the last couples of months or so, I will be closing this. If any of the maintainers want to do it by themselves, feel free to apply the diff manually and fix any of the pending changes (would prefer if I'm *not* being attributed in the commit).

2025-05-06 10:22 UTC, closed without merging