Add: Traditional Chinese README.md.
PerformanC/ReZygisk pull request #84
Opened 2024-11-15 00:07 UTC by RejectVanity

## Changes

Create a Traditional Chinese README, specify the file name for the Simplified Chinese README, and store both in the "READMEs" directory.

(Standardize the filename of the Simplified Chinese README according to the IETF language tag standard.)

## Why 

Write here why you think this should be merged

## Checkmarks

- [x] The modified functions have been tested.
- [x] Used the same indentation as the rest of the project.
- [x] Updated documentation (changelog).

## Additional information

I accidentally closed pull request #81 recently. Now, I have created a new pull request (#84) and also synchronized the latest changes from #80 into it.

2024-11-15 20:19 UTC, ThePedroo approved these changes
LGTM!

2024-11-15 20:21 UTC, ThePedroo requested changes
Actually, I missed something. Feel free to fix those in the Simplified Chinese too.

2024-11-15 20:21 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| 工具            | 說明                            |
The `|` must be aligned

2024-11-15 20:21 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| `Android NDK`   | Android 原生開發工具包     |
Ditto

2024-11-15 20:21 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| 依賴 | 說明                   |
Ditto

2024-11-15 20:21 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| `lsplt`    | Android 的簡單 PLT（程式連結表） 勾取   |
Ditto

2024-11-16 03:12 UTC, RainyXeon reviewed
Idk if it's possible to be aligned or not.
But imo, I prefer the `|` to be aligned in README_zh-TW

Let me know it's not possible

2024-11-16 03:16 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| `lsplt`   | Android 的簡單 PLT（程式連結表） 勾取            |
Can you just remove one space here? Then it will be the best that can be done.

2024-11-16 04:52 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| `lsplt`  | Android 的簡單 PLT（程式連結表） 勾取            |
```suggestion
| `lsplt`  | Android 的簡單 PLT（程式連結表） 勾取           |
```

Oh, I mean this.

2024-11-16 04:53 UTC, ThePedroo commented on READMEs/README_zh-TW.md
> +| `lsplt`  | Android 的簡單 PLT（程式連結表） 勾取            |
Please revert the last commit if possible: git reset --soft HEAD~1 and unstage the changes (the command to do so shows in git status)

2024-11-16 16:32 UTC, merged

2024-11-16 16:32 UTC, ThePedroo commented
Thank you!